### ISSUE TITLE
Wrong direction

### ISSUE THREAD

**Issue by cnc50** [FlyingSamson/SpaceMouseTool#14]
Installed plugin 1.3.0 under Windows 11
Object in Cura 5.2.1  moves in wrong direction. How can I change that?
Thanks

**Comment by FlyingSamson** [comment]
Have you tried reversing those directions in the configuration program that was installed with the driver for the space mouse ?

**Comment by cnc50** [comment]
I use this mouse with two other software programs (Freecad and Deskproto).
So it would be nice to change the directions only for Cura.


FlyingSamson ***@***.***> schrieb am Do., 12. Jan. 2023,
18:07:

**Comment by FlyingSamson** [comment]
You can change the behavior of the mouse in the configuration tool provided by 3DConnexion on a per-program basis. Just click on the Cura window to give it the focus before clicking on the configuration tool. I'm not sure if you then have to specifically select somewhere in that tool that you wish to make changes to the currently active program (Cura in this case) but this should definitely be possible.

**Comment by cnc50** [comment]
Hi,
great success. Followed your instructions and everything works properly.
 I`m so happy.
Best Regards
Stefan


Am Do., 12. Jan. 2023 um 19:17 Uhr schrieb FlyingSamson <
***@***.***>:

**Comment by FlyingSamson** [comment]
Glad to here it
