### ISSUE TITLE
missing Apple Silicon version

### ISSUE THREAD

**Issue by haaanz** [FlyingSamson/SpaceMouseTool#15]
Hello is it possible to provide arm64 version of the plugin? 

There is a plugin error during startup:

`pyspacemouse.cpython-310-darwin.so (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')`

**Comment by FlyingSamson** [comment]
I will give it a look.

**Comment by FlyingSamson** [comment]
@haaanz Please give v1.4.0 a try

**Comment by haaanz** [comment]
Works like charm!
Thanks a lot
