### ISSUE TITLE
Confirming it works on Big Sur, with a small catch

### ISSUE THREAD

**Issue by sethvoltz** [FlyingSamson/SpaceMouseTool#9]
I was able to install and use this on Big Sur by following the installation instructions, then going into the plugins folder and attempting to launch `lib/pyspacemouse.cpython-38-darwin.so` directly (choosing Cura as the app, just to get macOS to launch it) and then in the Security preference pane, allowing the launch, further [detailed here](pyspacemouse.cpython-38-darwin.so). When you allow it, Cura will re-launch and you will get an "invalid file" notification for the `.so` file, but it works from there as the plugin is able to load. This issue is also remediable by having an Apple authorized developer signature on the build

Thanks for the awesome plugin!

**Comment by FlyingSamson** [comment]
Thank you for that piece of information. I linked this issue in the Readme, so others on Big Sur will find it.
